emergency_alerts_utils/structured_logging.py
Add LogData DataClass to give some structure to the data written out to CloudWatch
- Writing json to CloudWatch allows the data to be queried
- The LogData class suggests required fields
Note: This is a starting point only and is not complete
=> EAS-481 Initial check-in of module to log queryable json CloudWatch

Dockerfile.eas-base, emergency_alerts_utils/structured_logging.py
As another step toward self-contained Fargate deployed microservices, the following changes have been made to the Emergency Alerts Utils repo:
- Empty default region when fetching from environment is causing test failure in emergency-alerts-api repo.
- Dockerfile has been refactored to have fewer layers
=> EAS-447 Add default region and refactor dockerfile for fewer layers

scripts/docker-build.sh
Replace hard-coded AWS account number with a call to the AWS CLI.
=> EAS-576 Get account number from AWS

Dockerfile.eas-base
The codebuild pipeline was failing due to errors with wheels and other tooling being out of date. Adding a separate upgrade step for the pip, wheels and setuptools packages fixed the issue.
=> EAS-880 Add upgrade step for pip, wheels and setuptools

Makefile
To avoid version ambiguity, use pip3 in the Makefile
=> Change makefile command to use pip3

emergency_alerts_utils/structured_logging.py
Cloudwatch logging should be blocked when running locally.
=> EAS-1034 Avoid boto3 error when running locally

Dockerfile.eas-base, emergency_alerts_utils/clients/zendesk/zendesk_client.py, scripts/docker-build.sh, tests/clients/zendesk/test_zendesk_client.py
Installing package `python3.9-dev` in the base image caused the ECR scan to raise the high-severity vulnerability warning:
[CVE-2022-42919](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2022-42919)	python3.9:3.9.5-3ubuntu0~20.04.1
The package has been removed from base and the functionality of the application verified in the preview environment.
It's likely that an intermediate version of the Docker.eas-base file required the package for a step that is no longer in the image.
=> EAS-1106 Fix high-severity ECR vulnerability

emergency_alerts_utils/clients/zendesk/zendesk_client.py, tests/clients/zendesk/test_zendesk_client.py
Fixes the metadata sent in the payload to Zendesk, via the API, replacing Notify with Emergency Alerts where applicable, and using the new Admin UI support form/field IDs for Emergency Alerts
=> Eas 1124 zendesk ticket metadata

emergency_alerts_utils/clients/encryption/encryption_client.py, tests/clients/encryption/test_encryption_client.py
---
When merging changes in the utils repository, the base image will need to be rebuilt, and then every other AMI after that.
This is to identify any issues that may crop up from making changes to utils (e.g., bumping package versions) early on.
If this is not done, it can obfuscate the origin of any potential issues that show up later.
=> Changing where the encryption library gets it's SALT and SECRET from

.github/workflows/on-pr-into-main.yml
---
When merging changes in the utils repository, the base image will need to be rebuilt, and then every other AMI after that.
This is to identify any issues that may crop up from making changes to utils (e.g., bumping package versions) early on.
If this is not done, it can obfuscate the origin of any potential issues that show up later.
=> NVM issue fix

.codepipeline/buildspec-base-build.yml
---
When merging changes in the utils repository, the base image will need to be rebuilt, and then every other AMI after that.
This is to identify any issues that may crop up from making changes to utils (e.g., bumping package versions) early on.
If this is not done, it can obfuscate the origin of any potential issues that show up later.
=> Abstract region, account number and tags from buildspec

emergency_alerts_utils/logging.py, setup.py
This PR consists of:
- Updated version of python-json-logger
- Adjustment to where JsonFormatter imported from
---
=> Changed how JsonFormatter referenced in imports

emergency_alerts_utils/admin_action.py, emergency_alerts_utils/api_key.py
For future changes in https://github.com/alphagov/emergency-alerts-api/pull/190 and https://github.com/alphagov/emergency-alerts-admin/pull/220 we can centralise these small constants.
I'm assuming this will need to be merged before future runs in the other repositories can pick this up.
=> EAS-2569: Add constants for admin approvals

.codepipeline/buildspec-base-build.yml
This PR removes the tag checkout in the `buildspec.yml`. It has been agreed that this is a historical artefact, from a time where CodePipeline was not capable of sourcing a particular commit hash, so there was no way to actually run a pipeline with a non-HEAD commit - or even a commit that wasn't latest@main, because generally it's inadvisable to change the source branch of the pipeline, as that's a permanent configuration difference that does class as a form of infra drift.
Nowadays (and as of [November 2023](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-codepipeline-pipeline-execution-source-revision-overrides/)) you can use the `source revision override` feature to run CodePipeline on an arbitrary commit hash. Given our main concern was facilitating quick rollbacks or …
=> Remove checkout to tag in Buildspec

emergency_alerts_utils/admin_action.py
As title, this adds a few new constants as per the ticket. We'll have a new action type (thus allowing another admin to approve) and some associated timeouts.
This will be required for the API (and soon admin) CI to succeed so I thought I'd get it in early.
---
=> EAS-2173: Utils: Add constants for elevation admin action type

.github/workflows/on-pr-into-main.yml
This PR adds the ability for PR checks to be run on pull requests to the main branch even when they are in a draft state. Currently, they only run when the PR is in a "Ready for review" state, which isn't very helpful in instances where you want an easy way of checking the build status of your work on the branch itself, without indicating to other people that you would like your PR to be reviewed. 
Corresponding PRs will be made for Utils, API, Admin, and gov.uk/alerts
---
This is to identify any issues that may crop up across the application as a result …
=> Run PR checks on the branch even when the corresponding PR is in draft

emergency_alerts_utils/xml/cap.py, emergency_alerts_utils/xml/common.py
Migrated from API to be used in admin too.
---
=> EAS-2602 + EAS-2603: Utils: Add constants used for XML generation

emergency_alerts_utils/admin_action.py, emergency_alerts_utils/clients/zendesk/zendesk_client.py, tests/clients/zendesk/test_zendesk_client.py
As title, we now have some new constants defining 'out of hours' for admin elevation-related requests. We also enhance the ZenDesk client to be able to search for existing tickets referencing them and provide a method to edit the priority of said existing ticket. Since the intention is to go to PagerDuty while having different priorities I've also introduced a `custom_priority` field so we can still use `P1=True`.
---
This is to identify any issues that may crop up across the application as a result of making changes to utils (e.g., bumping package …
=> EAS-2653: Utils: Add out of hours admin constants and enhance ZenDesk client to edit

setup.py
=> EAS-2692 Force Werkzeug version bump

Dockerfile.eas-base
This is used in the Makefile(s) to embed the version information into version.py in the containers, so is needed in the base image when the sub project Dockerfile(s) are executing.
---
=> EAS-2056: Utils: Add envsubst to container

.github/dependabot.yml
=> Dependabot: Scan Docker and Pip upgrades
